
# training settings and hyperparameters for medium-augmentation COCO training

task: detect
mode: train

# Train settings
model: 
data: 
epochs: 200  # Adjusted from 300
patience: 50
batch: 32  # Adjusted from 16
imgsz: 416  # Adjusted from 640
save: True
save_period: -1
cache: False
device: 
workers: 8
project: 
name: 
exist_ok: False
pretrained: True
optimizer: auto
verbose: True
seed: 0
deterministic: True
single_cls: False
rect: False
cos_lr: False
close_mosaic: 10
resume: False
amp: True
fraction: 1.0
profile: False

# Segmentation
overlap_mask: True
mask_ratio: 4

# Classification
dropout: 0.0

# Val/Test settings
val: True
split: val
save_json: False
save_hybrid: False
conf: 0.5  # Adjusted from 0.25
iou: 0.7
max_det: 300
half: True
dnn: False
plots: True

# Prediction settings
source: 
show: False
save_txt: False
save_conf: False
save_crop: False
show_labels: True
show_conf: True
vid_stride: 1
line_width:  
visualize: False
augment: False
agnostic_nms: False
classes: 
retina_masks: False
boxes: True

# Export settings
format: torchscript
keras: False
optimize: False
int8: False
dynamic: False
simplify: False
opset: 
workspace: 4
nms: False

# Hyperparameters
lr0: 0.0001  # Adjusted from 0.001
lrf: 0.01
momentum: 0.937  # Unchanged
weight_decay: 0.0005
warmup_epochs: 3.0
warmup_momentum: 0.8
warmup_bias_lr: 0.1
box: 7.5
cls: 0.5
dfl: 1.5
pose: 1.0
kobj: 1.0
label_smoothing: 0.0
nbs: 64
hsv_h: 0.015
hsv_s: 0.7
hsv_v: 0.4
degrees: 0.0
translate: 0.1
scale: 0.5
shear: 0.0
perspective: 0.0
flipud: 0.0
fliplr: 0.5
mosaic: 1.0
mixup: 0.0
copy_paste: 0.0

# Custom config.yaml ---------------------------------------------------------------------------------------------------
cfg:  # (str, optional) for overriding defaults.yaml

# Debug, do not modify -------------------------------------------------------------------------------------------------
v5loader: False  # (bool) use legacy YOLOv5 dataloader (deprecated)

# Tracker settings ------------------------------------------------------------------------------------------------------
tracker: botsort.yaml  # (str) tracker type, choices=[botsort.yaml, bytetrack.yaml]
